# Generated by Django 5.2 on 2025-05-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_serveur_administrateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
    ]
